import type {OrchestrateResponse} from '../api/contracts';
import {obj,rows,money,date,text,State} from './cockpit';
export default function AssetIncomeTargets({data,ticker}:{data:OrchestrateResponse|null;ticker:string}){
 const market=obj(obj(data?.result.workspace_intelligence).market_context);
 const asset=obj(obj(market.tickers)[ticker]);
 const targets=obj(asset.institution_targets),dividends=obj(asset.issuer_dividends);
 const targetRows=rows(targets.rows),events=rows(dividends.events);
 return <section className="panel" aria-label="Proventos e alvos com fontes"><h2>Alvos institucionais e proventos · {ticker}</h2><p>Opiniões individuais das instituições; não representam consenso nem retorno esperado. Consulta somente à evidência armazenada qualificada.</p>{targetRows.length?<div className="table-wrap"><table><thead><tr><th>Instituição</th><th>Alvo</th><th>Publicação</th><th>Horizonte</th><th>Fonte</th></tr></thead><tbody>{targetRows.map((r,i)=><tr key={String(r.document_id??i)}><td>{text(r.institution)}</td><td>{money(r.price_brl)}</td><td>{date(r.published_at)}</td><td>{text(r.horizon_date)}</td><td>{typeof r.source_url==='string'&&r.source_url.startsWith('https://')?<a href={r.source_url} target="_blank" rel="noreferrer">Relatório original</a>:'Fonte indisponível'}</td></tr>)}</tbody></table></div>:<State kind="limited" title="Sem alvo primário admissível">Estado da consulta: {text(targets.status)}. Ausência de alvo não permite inferir preço justo.</State>}<h3>Dividendos e JCP</h3><p>Estado da coleta: {text(dividends.collection_status)} · cobertura: {text(dividends.coverage_status)}. Anúncio não garante recebimento pessoal.</p>{events.length?<div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Bruto por ação</th><th>Anúncio</th><th>Data-com</th><th>Ex</th><th>Pagamento</th><th>Fonte</th></tr></thead><tbody>{events.map((r,i)=><tr key={String(r.source_record_id??i)}><td>{text(r.payment_type)}</td><td>{money(r.gross_amount_per_share_brl)}</td><td>{text(r.announcement_date)}</td><td>{text(r.record_date)}</td><td>{text(r.ex_date)}</td><td>{text(r.payment_date)}</td><td>{text(r.source)}</td></tr>)}</tbody></table></div>:<p>Nenhum evento de provento elegível neste corte. Isso não prova ausência de pagamento futuro.</p>}</section>;
}
