import {useEffect,useState} from 'react';
import {b3Api} from '../api/client';
import AnalysisOutput from './AnalysisOutput';
import PersonalHistory from './PersonalHistory';
import type {OrchestrateResponse,PortfolioSnapshot,CapitalProfile} from '../api/contracts';
import {getPageDefinition} from '../app/pages';
import {Metric,State,obj,money,rows,num,Source} from './cockpit';
export function HistoryWorkspace({ticker,onSelect}:{ticker:string;onSelect:(s:string)=>void}){
 const [tab,setTab]=useState('operations'),[symbol,setSymbol]=useState(ticker),[since,setSince]=useState(''),[value,setValue]=useState<Record<string,unknown>|null>(null),[answer,setAnswer]=useState<OrchestrateResponse|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setSymbol(ticker)},[ticker]);
 async function fetch(){setLoading(true);setError('');setAnswer(null);try{const v=await b3Api.personalHistory(symbol,since);setValue(v);onSelect(symbol);if(tab!=='operations'&&(num(v.learning_sample_size)??0)>0){const t=getPageDefinition('History & Learning').tabs!.find(t=>t.id===tab)!;setAnswer(await b3Api.orchestrate({task:t.prompt,ticker:symbol||null,context:{workspace:'History & Learning',selected_ticker:symbol||null,history_since:since||null,research_mode:'stored_only'}}))}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 return <><div className="workspace-tabs" role="tablist">{getPageDefinition('History & Learning').tabs!.map(t=><button key={t.id} role="tab" aria-selected={tab===t.id} className={tab===t.id?'selected':''} onClick={()=>{setTab(t.id);setAnswer(null)}}>{t.label}</button>)}</div><section className="panel"><h2>Experiência pessoal e proveniência</h2><form className="inline-controls" onSubmit={e=>{e.preventDefault();void fetch()}}><label>Ativo (vazio = todos)<input aria-label="Ativo do histórico" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="PETR4"/></label><label>Desde<input aria-label="Início do histórico" type="date" value={since} onChange={e=>setSince(e.target.value)}/></label><button disabled={loading}>Consultar histórico</button></form>{loading&&<State kind="loading" title="Consultando evidências">Lendo operações da base canônica.</State>}{error&&<State kind="error" title="Histórico indisponível">{error}</State>}{value&&tab==='operations'&&<PersonalHistory value={value}/>}<AnalysisOutput data={answer}/>{value&&tab!=='operations'&&<div className="cards"><Metric label="Execuções observadas" value={num(value.execution_count)??'Indisponível'}/><Metric label="Amostra elegível para aprendizado" value={num(value.learning_sample_size)??'Indisponível'}/><Metric label="Similaridade validada" value={value.validated_similarity==null?'Indisponível':String(value.validated_similarity)}/></div>}{tab!=='operations'&&!answer&&<State kind="limited" title={tab==='learnings'?'Aprendizados · LIMITED':'Similaridade · LIMITED'}>Desfechos econômicos e ownership canônico precisam estar estabelecidos. Solicite a análise para consultar o estado real; nenhuma estratégia ou precedente é inventado.</State>}{!value&&!loading&&!error&&<State title="Reconstrua suas operações">Escolha um ativo e período. As fontes e sequências observadas aparecerão aqui.</State>}</section></>;
}
export function RiskWorkspace({ticker,onRun,result,busy}:{ticker:string;onRun:(task:string,context:Record<string,unknown>)=>void;result:OrchestrateResponse|null;busy:boolean}){
 const [symbol,setSymbol]=useState(ticker),[shock,setShock]=useState('-10');
 const scenario=obj(result?.result.scenario_result);
 return <><section className="panel"><div className="section-head"><div><h2>Simular um choque explícito</h2><p>Você informa a hipótese; o backend calcula o impacto.</p></div><span className="badge warning">Cenário, não previsão</span></div><form className="lab-form" onSubmit={e=>{e.preventDefault();const s=symbol.trim().toUpperCase();onRun(`UC-11 stress: ${s} ${shock}%. Não inferir beta ou repricing de opções.`,{dashboard_page:'Risk & Stress',use_cases:['UC-11'],ticker_price_shocks:{[s]:Number(shock)/100},analysis_mode:'deterministic'})}}><label>Ativo<input required pattern="[A-Z]{4}[0-9]{1,2}" aria-label="Ativo do stress" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="PETR4"/></label><label>Choque de preço (%)<input required type="number" min="-99.9" step="0.1" aria-label="Choque de preço" value={shock} onChange={e=>setShock(e.target.value)}/></label><button disabled={busy}>Simular impacto</button></form><State kind="limited" title="Premissas explícitas">Choque aplicado somente ao ativo informado. Reprecificação de opções, beta e probabilidades não são presumidos.</State></section>{Object.keys(scenario).length>0&&<div className="cards"><Metric label="Impacto no cenário" value={money(scenario.portfolio_pnl)}/><Metric label="Valor sob stress" value={money(scenario.stressed_portfolio_value)}/><Metric label="Capital de exercício" value={money(scenario.assignment_capital)}/><Metric label="Qualidade" value={String(scenario.quality_status??'Indisponível')}/></div>}{Object.keys(scenario).length>0&&<section className="panel"><h2>Impacto por posição</h2><Source asOf={scenario.as_of} source={Array.isArray(scenario.source_refs)?scenario.source_refs.join(' · '):undefined}/><div className="table-wrap"><table><thead><tr><th>Ativo</th><th>Base</th><th>Sob stress</th><th>Impacto</th><th>Choque aplicado</th></tr></thead><tbody>{rows(scenario.position_stress).map(r=><tr key={String(r.position_id)}><td>{String(r.ticker)}</td><td>{money(r.base_value)}</td><td>{money(r.stressed_value)}</td><td>{money(r.pnl_impact)}</td><td>{num(r.applied_shock)===null?'Indisponível':new Intl.NumberFormat('pt-BR',{style:'percent'}).format(num(r.applied_shock)!)}</td></tr>)}</tbody></table></div><p className="muted">Valores calculados pelo backend. Este motor aplica choque linear ao valor das posições do ativo, incluindo opções; não representa repricing por Greeks ou IV.</p></section>}<AnalysisOutput data={result}/></>;
}
export function OverviewWorkspace({portfolio,capital,onNavigate}:{portfolio:PortfolioSnapshot|null;capital:CapitalProfile|null;onNavigate:(p:string)=>void}){
 const risk=obj(obj(portfolio?.intelligence).capital_risk),exposures=rows(obj(portfolio?.intelligence).exposures).sort((a,b)=>(num(b.weight)??0)-(num(a.weight)??0));
 return <><div className="cards"><Metric label="Capital utilizável" value={money(capital?.usable_capital)}/><Metric label="Exposição a PUTs" value={money(risk.assignment_capital)}/><Metric label="Posições" value={portfolio?.positions.length??'Indisponível'}/><Metric label="Ações CALL sem cobertura" value={String(risk.uncovered_call_shares??'Indisponível')}/></div><Source asOf={portfolio?.as_of} source={portfolio?.source_refs?.join(' · ')}/><section className="panel"><h2>Da carteira à decisão</h2><div className="decision-tiles">{[['Portfolio','Entenda concentração e exposição.'],['Options','Investigue posições, cotações e execuções.'],['Opportunities','Compare o universo pelo objetivo observado.'],['Strategy Lab','Coloque alternativas e premissas lado a lado.'],['Risk & Stress','Teste um choque explícito na carteira.'],['History & Learning','Verifique o que a experiência realmente sustenta.']].map(([p,d])=><button key={p} onClick={()=>onNavigate(p)}><strong>{p} →</strong><span>{d}</span></button>)}</div></section>{exposures.length===0&&<State title="Comece com a sua carteira">Carregue o snapshot BTG e as notas para obter contexto pessoal.</State>}</>;
}
