import {useState} from 'react';
import type {OrchestrateResponse} from '../api/contracts';
import AnalysisOutput from './AnalysisOutput';
import {obj,rows,num,text,date,Metric,State,Source} from './cockpit';

export default function MarketContext({tab,data,busy}:{tab:string;data:OrchestrateResponse|null;busy:boolean}){
 const [query,setQuery]=useState(''),[since,setSince]=useState('');
 const context=obj(obj(data?.result.workspace_intelligence).market_context),macro=obj(context.macro);
 const events=rows(context.market_overview_research).filter(e=>(!query||[e.headline,e.title,e.summary,e.source].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!since||String(e.published_at??e.available_timestamp??'')>=since));
 if(!data)return <State kind={busy?'loading':'empty'} title={busy?'Consultando contexto':'Consulte o estado real do mercado'}>Macro e evidências serão apresentados com as datas originais. Valores não disponíveis permanecem desconhecidos.</State>;
 return <><div role="status" aria-live="polite"><span aria-hidden="true" style={{color:busy?'#eab308':data.error?'#ef4444':'#22c55e'}}>● </span>{busy?'Em processamento · análise anterior preservada':data.error?'Falha na análise':'Análise concluída · confira a cobertura das fontes'}</div><section className="analysis-summary context-evidence"><h2>Análise do agente B3</h2><AnalysisOutput data={data}/></section><Source asOf={context.as_of??data.result.as_of} source={data.sources.join(' · ')}/>{data.error&&<State kind="error" title="Contexto indisponível">{data.error}</State>}
 {tab==='regime'&&<><div className="cards">{['SELIC','CDI','IPCA'].map(key=>{const r=obj(macro[key]);return <Metric key={key} label={key} value={num(r.value)===null?'Indisponível':`${num(r.value)?.toLocaleString('pt-BR')} ${text(r.unit)}`} detail={`Observação: ${date(r.observation_timestamp)}`}/>})}</div><State kind="limited" title="Regime calibrado e séries macro · LIMITED">O contrato consultado retorna observações macro e research. Uma classificação calibrada de regime, série de Ibovespa, dólar, VIX e fluxo não foi fornecida nesta resposta. Não derivamos esses sinais no navegador.</State></>}
 {tab==='factors'&&<State kind="limited" title="Estudos de fatores · LIMITED">Esta resposta não contém estudo estatístico tipado com amostra, efeito, holdout e correção de múltiplos testes. Notícias não substituem validação. Associação não é causalidade.</State>}
 {tab==='research'&&<><div className="section-head"><h3>Timeline de evidências ({events.length})</h3><div className="inline-controls"><input aria-label="Buscar evento de mercado" placeholder="Buscar evento ou fonte" value={query} onChange={e=>setQuery(e.target.value)}/><label>Publicado desde<input aria-label="Publicação inicial" type="date" value={since} onChange={e=>setSince(e.target.value)}/></label></div></div><div className="event-timeline">{events.map((e,i)=>{const ref=String(e.url??e.source_ref??''),title=text(e.headline??e.title??e.event_type);return <article className="research-event" key={String(e.source_record_id??i)}><small>{date(e.published_at??e.available_timestamp)} · {text(e.source_name??e.source)}</small><h3>{ref.startsWith('https://')?<a href={ref} target="_blank" rel="noreferrer">{title}</a>:title}</h3>{Boolean(e.summary)&&<p>{String(e.summary)}</p>}<span className="badge">{text(e.impact_classification??e.relationship??'Impacto não classificado')}</span>{Boolean(e.ticker)&&<span className="badge">{String(e.ticker)}</span>}</article>})}</div>{!events.length&&<State title="Nenhum evento para este corte e filtro">Altere o filtro ou a política de consulta. Ausência de evento não confirma uma tese.</State>}</>}
</>;
}
