import {useState} from 'react';
import {ResponsiveContainer,ScatterChart,Scatter,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import type {OrchestrateResponse} from '../api/contracts';
import AnalysisOutput from './AnalysisOutput';
import {rows,obj,num,money,percent,text,State,Metric,Source} from './cockpit';
export default function OpportunityExplorer({data,onCompare,onSelect}:{data:OrchestrateResponse|null;onCompare:(s:string)=>void;onSelect:(s:string)=>void}){
 const [membership,setMembership]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState('');
 const screen=obj(data?.result.opportunity_screen),universe=rows(screen.rows),filtered=universe.filter(r=>text(r.ticker).includes(query.toUpperCase())&&(membership==='all'||obj(r.portfolio).held===(membership==='held')));
 const detail=universe.find(r=>r.ticker===selected);
 const plot=filtered.filter(r=>num(r.volatility_60d)!==null&&num(r.liquidity_proxy_20d)!==null).map(r=>({...r,liquidity:r.liquidity_proxy_20d}));
 if(detail&&data){const evidence=obj(data.result.asset_evidence),history=obj(data.result.personal_history);const selectedData={...data,result:{...data.result,opportunity_screen:{...screen,rows:[detail]},asset_evidence:{[selected]:evidence[selected]},personal_history:{[selected]:history[selected]}}};return <section className="panel detail-panel"><div className="section-head"><div><h2>{selected} · análise da oportunidade</h2><p>Fatos do ativo selecionado · objetivo {text(screen.objective)}</p></div><div className="action-row"><button onClick={()=>onCompare(selected)}>Comparar no Strategy Lab</button><button className="ghost" onClick={()=>setSelected('')}>Voltar ao ranking</button></div></div><Source asOf={detail.quote_as_of} source={Array.isArray(detail.source_refs)?detail.source_refs.join(' · '):undefined}/><div className="cards"><Metric label="Preço da fonte" value={money(detail.current_price)}/><Metric label="Rank canônico" value={num(detail.rank)??'Sem rank'}/><Metric label="Volatilidade observada" value={percent(detail.volatility_60d)}/><Metric label="Proxy de liquidez 20d" value={money(detail.liquidity_proxy_20d)}/></div><State title="Por que apareceu?" kind="limited">Este ativo está no universo solicitado. A ordenação considera o objetivo explícito, não uma recomendação geral de compra. Retorno esperado e score geral permanecem desconhecidos quando não fornecidos.</State><AnalysisOutput data={selectedData}/></section>}
 return <><div className="cards"><Metric label="Ativos analisados" value={data?universe.length:'Aguardando análise'}/><Metric label="Ordenação" value={Object.keys(screen).length?text(screen.status).replaceAll('_',' '):'Indisponível'} detail="Condicionada ao objetivo escolhido"/><Metric label="Score geral" value="Indisponível" detail="Não substituímos risco ou liquidez por valuation"/></div>{Object.keys(screen).length>0&&<Source asOf={data?.result.as_of} source={text(screen.policy_version)}/>}
 {plot.length>1&&<section className="panel"><h2>Risco observado × liquidez</h2><p className="muted">Volatilidade de 60 retornos versus proxy retornada pelo backend; não é retorno esperado.</p><div className="chart-canvas compact"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top:10,right:30,bottom:20,left:30}}><CartesianGrid stroke="#203a50"/><XAxis dataKey="volatility_60d" name="Volatilidade" type="number" tickFormatter={percent}/><YAxis dataKey="liquidity" name="Liquidez" type="number" tickFormatter={v=>Number(v).toLocaleString('pt-BR',{notation:'compact'})}/><Tooltip contentStyle={{background:'#102436',border:'1px solid #45647e'}} cursor={{strokeDasharray:'3 3'}}/><Scatter isAnimationActive={false} name="Ativos observados" data={plot} fill="#41bbff" onClick={r=>{setSelected(String(obj(r.payload).ticker));onSelect(String(obj(r.payload).ticker))}}/></ScatterChart></ResponsiveContainer></div></section>}
 <section className="panel"><div className="section-head"><h2>Universo e oportunidades</h2><div className="inline-controls"><input aria-label="Filtrar oportunidades" placeholder="Filtrar ticker" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar presença na carteira" value={membership} onChange={e=>setMembership(e.target.value)}><option value="all">Todas</option><option value="held">Na carteira</option><option value="outside">Fora da carteira</option></select></div></div><div className="table-wrap"><table><thead><tr>{['Rank','Ativo','Carteira','Preço','Volatilidade 60d','Qualidade','Detalhe'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={text(r.ticker)} className={r.ticker===selected?'selected-row':''}><td>{num(r.rank)??'—'}</td><td><button className="text-button" onClick={()=>{setSelected(text(r.ticker));onSelect(text(r.ticker))}}>{text(r.ticker)}</button></td><td>{obj(r.portfolio).held===true?'Na carteira':obj(r.portfolio).held===false?'Fora':'Desconhecida'}</td><td>{money(r.current_price)}</td><td>{percent(r.volatility_60d)}</td><td>{Array.isArray(r.exclusions)&&r.exclusions.length?'Limitada':'Consulte evidências'}</td><td><button className="ghost" onClick={()=>{setSelected(text(r.ticker));onSelect(text(r.ticker))}}>Abrir análise</button></td></tr>)}</tbody></table></div>{!filtered.length&&<State title={data?'Nenhum ativo no filtro':'Escolha o universo e analise'}>Os ranks só aparecem quando o backend estabelece comparabilidade. Ajuste o filtro ou solicite uma análise.</State>}</section>

 {!detail&&data&&<details className="panel"><summary>Evidências, metodologia e comparação completa</summary><AnalysisOutput data={data}/></details>}</>;
}
