import {useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import type {PortfolioSnapshot,CapitalProfile,OrchestrateResponse} from '../api/contracts';
import {obj,rows,num,money,percent,date,Metric,State,Source} from './cockpit';
type PerShareIncome={value:number|null;complete:boolean;records:number};
function perShareIncome(portfolio:PortfolioSnapshot|null,ticker:string,type:'DIVIDEND'|'JCP'):PerShareIncome{
 const payments=portfolio?.received_income?.payments.filter(p=>p.ticker===ticker&&p.payment_type===type)??[];
 const usable=payments.filter(p=>p.quantity!=null&&p.quantity>0&&p.net_amount!=null&&Number.isFinite(p.net_amount));
 const missing=payments.length-usable.length;
 return {value:usable.length?usable.reduce((sum,p)=>sum+(p.net_amount as number)/(p.quantity as number),0):null,complete:payments.length>0&&missing===0,records:payments.length};
}
export default function PortfolioWorkspace({portfolio,capital,result,onSelect,onNavigate}:{portfolio:PortfolioSnapshot|null;capital:CapitalProfile|null;result:OrchestrateResponse|null;onSelect:(s:string)=>void;onNavigate:(page:string,s:string)=>void}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('value'),[selected,setSelected]=useState('');
 const intelligence=obj(portfolio?.intelligence),risk=obj(intelligence.capital_risk),exposures=rows(intelligence.exposures);
 const positions=(portfolio?.positions??[]).filter(p=>p.instrument_type==='STOCK');
 const filtered=positions.filter(p=>p.ticker.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='ticker'?a.ticker.localeCompare(b.ticker):Math.abs(b.market_value??0)-Math.abs(a.market_value??0));
 const selectedPosition=positions.find(p=>p.ticker===selected);
 const pnl=rows(result?.result.position_pnl);
 const concentration=[...exposures].sort((a,b)=>(num(b.weight)??0)-(num(a.weight)??0)).slice(0,8);
 return <><div className="cards"><Metric label="Capital utilizável" value={money(capital?.usable_capital)} detail={`Reserva ${money(capital?.minimum_reserve)}`}/><Metric label="Capital para exercício de PUTs" value={money(risk.assignment_capital)} detail="Exposição calculada pelo backend"/><Metric label="Posições no snapshot" value={portfolio?.positions.length??'Indisponível'} detail="Ações e opções · fonte BTG"/><Metric label="Caixa após exercício" value={money(risk.cash_after_assignment)} detail="Caixa informado na base canônica"/></div><Source asOf={portfolio?.as_of} source={portfolio?.source_refs?.join(' · ')}/>
 {concentration.length>0&&<section className="panel"><div className="section-head"><div><h2>Onde a carteira está concentrada</h2><p>Exposições por ativo, incluindo posições de opções.</p></div><span className="badge">Backend · snapshot</span></div><div className="exposure-layout"><div className="chart-canvas compact"><ResponsiveContainer width="100%" height="100%"><BarChart data={concentration} layout="vertical" margin={{left:10,right:25}}><CartesianGrid stroke="#203a50" horizontal={false}/><XAxis type="number" tickFormatter={percent} stroke="#97b2ca"/><YAxis type="category" dataKey="ticker" width={65} stroke="#bdd0e0"/><Tooltip contentStyle={{background:'#102436',border:'1px solid #45647e'}} formatter={v=>percent(v)}/><Bar isAnimationActive={false} dataKey="weight" name="Peso na carteira" fill="#298fff" radius={[0,4,4,0]} onClick={d=>{const s=String(obj(d.payload).ticker);setSelected(s);onSelect(s)}}/></BarChart></ResponsiveContainer></div><div className="insight-list"><h3>Para investigar</h3>{concentration.slice(0,3).map(e=><button key={String(e.ticker)} onClick={()=>{setSelected(String(e.ticker));onSelect(String(e.ticker))}}><span>{String(e.ticker)} · peso {percent(e.weight)}</span><small>Capital para PUTs {money(e.assignment_capital)} →</small></button>)}</div></div></section>}
 <section className="panel"><div className="section-head"><div><h2>Ações na carteira</h2><p>{filtered.length} posições · valores do snapshot; não são cotações live.</p></div><div className="inline-controls"><input aria-label="Buscar posição" placeholder="Buscar ativo" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Ordenar posições" value={sort} onChange={e=>setSort(e.target.value)}><option value="value">Exposição absoluta</option><option value="ticker">Ativo A–Z</option></select></div></div><div className="table-wrap"><table><thead><tr>{['Ativo','Quantidade','Custo médio','Preço snapshot','Valor atual','P&L não realizado','Dividendos líquidos/ação','JCP líquido/ação','Recebidos líquidos','Peso'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{filtered.map(p=>{const income=portfolio?.received_income?.summaries.find(s=>s.ticker===p.ticker),dividend=perShareIncome(portfolio,p.ticker,'DIVIDEND'),jcp=perShareIncome(portfolio,p.ticker,'JCP'),exposure=exposures.find(e=>e.ticker===p.ticker),mark=pnl.find(r=>r.position_id===p.position_id);return <tr key={p.position_id} className={selected===p.ticker?'selected-row':''}><td><button className="text-button" onClick={()=>{setSelected(p.ticker);onSelect(p.ticker)}}>{p.ticker}</button>{p.quantity<0&&<span className="badge warning">SHORT</span>}</td><td>{p.quantity.toLocaleString('pt-BR')}</td><td>{money(p.average_cost)}</td><td>{money(p.market_price)}</td><td>{money(p.market_value)}</td><td className={num(mark?.unrealized_pnl)!<0?'negative':'positive'}>{money(mark?.unrealized_pnl)}</td><td>{dividend.value==null?'Sem registro':money(dividend.value)}<small className="muted">{dividend.records?(dividend.complete?'por ação · BTG':'por ação · cobertura parcial'):'por ação · sem registro'}</small></td><td>{jcp.value==null?'Sem registro':money(jcp.value)}<small className="muted">{jcp.records?(jcp.complete?'por ação · BTG':'por ação · cobertura parcial'):'por ação · sem registro'}</small></td><td>{income?money(income.total_net):'Sem registro'}</td><td>{percent(exposure?.weight)}</td></tr>})}</tbody></table></div>{!filtered.length&&<State title={positions.length?'Nenhuma posição corresponde à busca':'Nenhum snapshot de ações'}>Carregue o Excel BTG ou ajuste o filtro.</State>}</section>
 {selectedPosition&&<section className="panel detail-panel"><div className="section-head"><h2>{selected} · aprofundar análise</h2><button className="ghost" onClick={()=>setSelected('')}>Fechar detalhe</button></div><Source asOf={portfolio?.as_of} source={selectedPosition.source_ref}/><div className="action-row">{['Market Intelligence','Opportunities','Options','Strategy Lab','History & Learning'].map(p=><button key={p} onClick={()=>onNavigate(p,selected)}>{p}</button>)}</div></section>}
 <State title="Séries históricas e resultado econômico total · indisponíveis" kind="limited">O contrato atual não fornece evolução histórica da carteira, benchmark nem base agregada de aquisição. Dividendos recebidos permanecem separados do P&amp;L não realizado; não somamos valores no navegador.</State></>;
}
