import {useMemo,useState} from 'react';
import {ResponsiveContainer,ComposedChart,Line,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ReferenceLine,Brush} from 'recharts';
import type {StockMarketData} from '../api/contracts';
import {money,date,State} from './cockpit';
export default function PriceChart({records,averageCost}:{records:StockMarketData[];averageCost?:number|null}){
 const [volume,setVolume]=useState(true),[zoom,setZoom]=useState(false);
 const data=useMemo(()=>records.map(r=>({at:r.observation_timestamp,price:r.adjusted_close??r.close,volume:r.volume})),[records]);
 if(records.length<2)return <State title="Histórico insuficiente">Não há duas observações nesta janela. Escolha outro período.</State>;
 return <div className="interactive-chart"><div className="chart-controls"><label><input type="checkbox" checked={volume} onChange={e=>setVolume(e.target.checked)}/> Volume</label><label><input type="checkbox" checked={zoom} onChange={e=>setZoom(e.target.checked)}/> Zoom no período</label></div><div className="chart-canvas" role="img" aria-label={`Preço e volume em ${records.length} observações`}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:12,right:16,left:5,bottom:5}}><CartesianGrid stroke="#203a50" strokeDasharray="3 5"/><XAxis dataKey="at" tickFormatter={v=>date(v).slice(0,10)} minTickGap={50} stroke="#9bb2c7"/><YAxis yAxisId="price" domain={['auto','auto']} tickFormatter={money} width={85} stroke="#9bb2c7"/><YAxis yAxisId="volume" orientation="right" hide domain={[0,'dataMax * 4']}/><Tooltip contentStyle={{background:'#102436',border:'1px solid #45647e',borderRadius:8}} labelFormatter={v=>date(v)} formatter={(v,n)=>[n==='Preço'?money(v):Number(v).toLocaleString('pt-BR'),n]}/><Legend/>{volume&&<Bar isAnimationActive={false} yAxisId="volume" dataKey="volume" name="Volume (unidades)" fill="#31577a"/>}<Line isAnimationActive={false} yAxisId="price" dataKey="price" name="Preço" type="linear" stroke="#42b5ff" strokeWidth={2} dot={false} connectNulls={false}/>{averageCost!=null&&<ReferenceLine yAxisId="price" y={averageCost} stroke="#efba59" strokeDasharray="6 4" label="Custo médio"/>}{zoom&&<Brush dataKey="at" height={24} stroke="#4a8ec5" fill="#0c1e2e" tickFormatter={v=>date(v).slice(0,10)}/>}</ComposedChart></ResponsiveContainer></div><p className="chart-description">Fechamento ajustado quando fornecido; caso contrário, fechamento. Passe o cursor para consultar data, preço e volume.</p></div>;
}
