import {useState} from 'react';
import {b3Api} from './api/client';
import type {BrokerageOperation,PortfolioPosition,CurrentOptionRow,OrchestrateResponse} from './api/contracts';
import {money,rows,date,State,Source} from './components/cockpit';
type Props={positions:PortfolioPosition[];operations:BrokerageOperation[];ledgerAvailable:boolean;onSelect:(ticker:string)=>void;result?:OrchestrateResponse|null};
export default function OptionsWorkspace({positions,operations,ledgerAvailable,onSelect,result}:Props){
 const [tab,setTab]=useState('Posições'),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[underlying,setUnderlying]=useState(''),[chain,setChain]=useState<CurrentOptionRow[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[asOf,setAsOf]=useState(''),[page,setPage]=useState(0);
 const visible=positions.filter(p=>(!kind||p.option_type===kind)&&p.ticker.toLowerCase().includes(query.toLowerCase()));
 const notes=operations.filter(o=>o.option_ticker.toLowerCase().includes(query.toLowerCase()));
 const canonical=rows(result?.result.option_positions);
 async function fetchChain(){setLoading(true);setError('');try{const r=await b3Api.currentOptions(underlying,kind==='CALL'?'CALL':'PUT',150);setChain(r.options);setAsOf(r.as_of)}catch(e){setError(e instanceof Error?e.message:String(e));setChain([])}finally{setLoading(false)}}
 return <div className="options-workspace"><div className="workspace-tabs" role="tablist">{['Posições','Cadeia de opções','Execuções','Resultados'].map(t=><button role="tab" aria-selected={tab===t} className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="toolbar"><label>Buscar contrato<input aria-label="Buscar contrato" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="PETR…"/></label>{tab==='Posições'&&<label>Tipo<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">PUT e CALL</option><option>PUT</option><option>CALL</option></select></label>}</div>
 {tab==='Posições'&&<section className="panel"><div className="section-head"><h2>Posições abertas ({visible.length})</h2><span className="badge">Snapshot BTG</span></div><div className="table-wrap"><table><thead><tr>{['Ativo','Contrato','Tipo','Direção','Quantidade','Strike','Vencimento','DTE no snapshot','Preço entrada','Preço snapshot','Valor snapshot'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.position_id}><td>{p.underlying_ticker??'Indisponível'}</td><td><button className="text-button" onClick={()=>onSelect(p.ticker)}>{p.ticker}</button></td><td>{p.option_type}</td><td>{p.quantity<0?'Vendida':'Comprada'}</td><td>{p.quantity}</td><td>{money(p.strike)}</td><td>{p.expiration_date??'Indisponível'}</td><td>{String(canonical.find(r=>r.position_id===p.position_id)?.dte??'Indisponível')}</td><td>{money(p.average_cost)}</td><td>{money(p.market_price)}</td><td>{money(p.market_value)}</td></tr>)}</tbody></table></div>{!visible.length&&<State title="Nenhuma posição para este filtro">Ajuste os filtros ou importe o snapshot de opções.</State>}</section>}
 {tab==='Cadeia de opções'&&<section className="panel"><h2>Cotações e Greeks fornecidos pela OPLAB</h2><form className="inline-controls" onSubmit={e=>{e.preventDefault();void fetchChain()}}><label>Ativo<input required aria-label="Ativo da cadeia" value={underlying} onChange={e=>setUnderlying(e.target.value.toUpperCase())} placeholder="VALE3" pattern="[A-Z]{4}[0-9]{1,2}"/></label><label>Tipo<select value={kind||'PUT'} onChange={e=>setKind(e.target.value)}><option>PUT</option><option>CALL</option></select></label><button disabled={loading}>Consultar cadeia</button></form>{loading&&<State kind="loading" title="Consultando opções">Aguardando o provedor.</State>}{error&&<State kind="error" title="Cadeia indisponível">{error}</State>}<Source asOf={asOf} source="OPLAB"/><div className="table-wrap"><table><thead><tr>{['Contrato','Strike','Vencimento','Bid','Ask','Último','IV','Delta','Gamma','Theta','Vega','Volume','OI'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{chain.filter(r=>r.contract.option_id.toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.contract.option_id}><td><button className="text-button" onClick={()=>onSelect(r.contract.option_id)}>{r.contract.option_id}</button></td><td>{money(r.contract.strike)}</td><td>{r.contract.expiration_date}</td><td>{money(r.quote.bid)}</td><td>{money(r.quote.ask)}</td><td>{money(r.quote.last)}</td>{['implied_volatility','delta','gamma','theta','vega','volume','open_interest'].map(k=><td key={k}>{String(r.quote[k as keyof typeof r.quote]??'Indisponível')}</td>)}</tr>)}</tbody></table></div>{!chain.length&&!loading&&!error&&<State title="Escolha um ativo e consulte a cadeia">Nenhuma cotação foi carregada.</State>}</section>}
 {tab==='Execuções'&&<section className="panel"><h2>Execuções observadas ({notes.length})</h2><p className="muted">Fluxo recebido/pago na nota; não é lucro realizado. Vínculo com o ativo e fechamento não são inferidos.</p>{!ledgerAvailable&&<State kind="limited" title="Ledger indisponível">Importe notas de corretagem para reconstruir a história.</State>}<div className="table-wrap"><table><thead><tr>{['Data','Contrato','Direção','Quantidade','Preço','Fluxo bruto','Nota / fonte'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{notes.slice(page*30,page*30+30).map(o=><tr key={o.transaction_id}><td>{date(o.trade_date)}</td><td><button className="text-button" onClick={()=>onSelect(o.option_ticker)}>{o.option_ticker}</button></td><td>{o.side==='SELL'?'Venda':'Compra'}</td><td>{o.quantity}</td><td>{money(o.execution_price)}</td><td>{money(o.cash_flow)}</td><td><details><summary>{o.note_number??'Fonte'}</summary>{o.source_ref}</details></td></tr>)}</tbody></table></div><div className="pagination"><button disabled={!page} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1}</span><button disabled={(page+1)*30>=notes.length} onClick={()=>setPage(page+1)}>Próxima</button></div>{!notes.length&&ledgerAvailable&&<State title="Nenhuma execução para este filtro">Ajuste a busca ou carregue notas.</State>}</section>}
 {tab==='Resultados'&&<State kind="limited" title="Resultado mensal e acumulado · LIMITED">O endpoint de notas não certifica abertura, encerramento, exercício, rolagem e custos completos. Não convertemos fluxo de caixa em lucro. Consulte History &amp; Learning para ver a evidência observada e os requisitos de admissão.</State>}</div>;
}
